# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0a2 on Wed Jan 28 11:29:10 2026
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class puckutilityapp_frame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: puckutilityapp_frame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("Configure P3")
        self.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, "Burlingame Pro"))

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Calibrate Active Puck", "")
        self.Bind(wx.EVT_MENU, self.calibrate_all, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Calibrate All Active Pucks", "")
        self.Bind(wx.EVT_MENU, self.calibrate_all_pucks, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Update All Pucks (Firmware)", "")
        self.Bind(wx.EVT_MENU, self.update_all, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test Magnetic Encoder", "")
        self.Bind(wx.EVT_MENU, self.test_encoder, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Current Sense Bias", "")
        self.Bind(wx.EVT_MENU, self.calibrate_ibias, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Current Sense Gainfactor", "")
        self.Bind(wx.EVT_MENU, self.calibrate_igainfactor, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Current Sense Timing", "")
        self.Bind(wx.EVT_MENU, self.calibrate_itiming, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Current Sense Slope", "")
        self.Bind(wx.EVT_MENU, self.calibrate_islope, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Encoder Zero", "")
        self.Bind(wx.EVT_MENU, self.calibrate_enczero, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Encoder Direction", "")
        self.Bind(wx.EVT_MENU, self.calibrate_encdir, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Encoder Lag", "")
        self.Bind(wx.EVT_MENU, self.calibrate_enclag, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Set User Direction...", "")
        self.Bind(wx.EVT_MENU, self.set_user_dir, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Tune Gains...", "")
        self.Bind(wx.EVT_MENU, self.tune_gains, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Save to CSV...", "")
        self.Bind(wx.EVT_MENU, self.save_calibration, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Help", "")
        self.Bind(wx.EVT_MENU, self.open_support_page, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Exit", "")
        self.Bind(wx.EVT_MENU, self.exit_program, item)
        self.frame_menubar.Append(wxglade_tmp_menu, "Menu")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Flash...", "")
        self.Bind(wx.EVT_MENU, self.factory_flash, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Initialize Puck", "")
        self.Bind(wx.EVT_MENU, self.factory_initpuck, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test All", "")
        self.Bind(wx.EVT_MENU, self.factory_testall, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test Flash", "")
        self.Bind(wx.EVT_MENU, self.factory_testflash, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test RAM", "")
        self.Bind(wx.EVT_MENU, self.factory_testram, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test EEPROM", "")
        self.Bind(wx.EVT_MENU, self.factory_testee, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test Amplifier", "")
        self.Bind(wx.EVT_MENU, self.factory_testamp, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Test Encoder", "")
        self.Bind(wx.EVT_MENU, self.factory_testenc, item)
        self.frame_menubar.Append(wxglade_tmp_menu, "Factory")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.frame_statusbar = self.CreateStatusBar(2)
        self.frame_statusbar.SetStatusWidths([134, -1])
        # statusbar fields
        frame_statusbar_fields = ["Status:", "Ready"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.bitmap_button_1 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("images/BarrettLogoScaled-NoBG.png", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW | wx.BU_EXACTFIT)
        self.bitmap_button_1.SetMinSize((600, 100))
        self.bitmap_button_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.bitmap_button_1.SetMaxSize((600, 100))
        sizer_1.Add(self.bitmap_button_1, 0, wx.BOTTOM | wx.FIXED_MINSIZE, 5)

        grid_sizer_1 = wx.FlexGridSizer(6, 5, 5, 5)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 5)

        label_1 = wx.StaticText(self, wx.ID_ANY, "CAN Port:", style=wx.ALIGN_RIGHT)
        label_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.choice_port = wx.Choice(self, wx.ID_ANY, choices=["can0", "can1", "can2", "can3"])
        self.choice_port.SetMinSize((100, 34))
        self.choice_port.SetSelection(0)
        self.choice_port.SetMaxSize((100, 34))
        grid_sizer_1.Add(self.choice_port, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        self.button_1 = wx.Button(self, wx.ID_ANY, "Scan Pucks")
        self.button_1.SetMinSize((100, 34))
        self.button_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, "Burlingame Pro"))
        grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER, 0)

        label_9 = wx.StaticText(self, wx.ID_ANY, "Current:")
        label_9.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.VBus = wx.StaticText(self, wx.ID_ANY, "N/A", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.VBus.SetMinSize((50, 16))
        self.VBus.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, "Burlingame Pro"))
        grid_sizer_1.Add(self.VBus, 0, wx.ALIGN_CENTER, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "Select ID:", style=wx.ALIGN_RIGHT)
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.choice_id = wx.Choice(self, wx.ID_ANY, choices=["None"])
        self.choice_id.SetMinSize((100, 34))
        self.choice_id.SetSelection(0)
        self.choice_id.SetMaxSize((100, 34))
        grid_sizer_1.Add(self.choice_id, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, "Puck Temp:")
        label_5.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.PTemp = wx.StaticText(self, wx.ID_ANY, "N/A", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.PTemp.SetMinSize((50, 16))
        self.PTemp.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, "Burlingame Pro"))
        grid_sizer_1.Add(self.PTemp, 0, wx.ALIGN_CENTER, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, "New ID:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.text_id = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.text_id.SetMinSize((100, 34))
        grid_sizer_1.Add(self.text_id, 0, wx.ALIGN_CENTER | wx.RESERVE_SPACE_EVEN_IF_HIDDEN, 0)

        self.button_2 = wx.Button(self, wx.ID_ANY, "Set")
        self.button_2.SetMinSize((100, 34))
        grid_sizer_1.Add(self.button_2, 0, 0, 0)

        label_8 = wx.StaticText(self, wx.ID_ANY, "Mot. Temp:")
        label_8.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.LEFT, 5)

        self.MTemp = wx.StaticText(self, wx.ID_ANY, "N/A", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.MTemp.SetMinSize((50, 16))
        self.MTemp.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, "Burlingame Pro"))
        grid_sizer_1.Add(self.MTemp, 0, wx.ALIGN_CENTER, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, "Version:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.text_version = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_version.SetMinSize((100, 34))
        self.text_version.Enable(False)
        grid_sizer_1.Add(self.text_version, 0, wx.ALIGN_CENTER, 0)

        self.button_8 = wx.Button(self, wx.ID_ANY, "Update...")
        self.button_8.SetMinSize((100, 34))
        grid_sizer_1.Add(self.button_8, 0, 0, 0)

        label_10 = wx.StaticText(self, wx.ID_ANY, "RPM:")
        label_10.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.Vrpm = wx.StaticText(self, wx.ID_ANY, "N/A", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.Vrpm.SetMinSize((50, 16))
        self.Vrpm.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, "Burlingame Pro"))
        grid_sizer_1.Add(self.Vrpm, 0, wx.ALIGN_CENTER, 0)

        label_7 = wx.StaticText(self, wx.ID_ANY, "Configure:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_7.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Burlingame Pro"))
        grid_sizer_1.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.button_10 = wx.Button(self, wx.ID_ANY, "Browse...")
        self.button_10.SetMinSize((100, 34))
        grid_sizer_1.Add(self.button_10, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.choice_test = wx.Choice(self, wx.ID_ANY, choices=["Idle", "Trq (mNm)", "Vel (RPM)", "Pos (deg)", "Homing"])
        self.choice_test.SetMinSize((124, 34))
        self.choice_test.SetSelection(0)
        self.choice_test.SetMaxSize((124, 34))
        grid_sizer_1.Add(self.choice_test, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        self.text_testvalue = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE | wx.TE_PROCESS_ENTER)
        self.text_testvalue.SetMinSize((100, 34))
        grid_sizer_1.Add(self.text_testvalue, 0, wx.ALIGN_CENTER, 0)

        self.button_6 = wx.Button(self, wx.ID_ANY, "Go")
        self.button_6.SetMinSize((100, 34))
        grid_sizer_1.Add(self.button_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.Dial = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("images/dialnobgcroppedscaled.png", wx.BITMAP_TYPE_ANY))
        self.Dial.SetMinSize((60, 60))
        grid_sizer_1.Add(self.Dial, 0, wx.ALIGN_CENTER, 0)

        self.onoffpanel = wx.Panel(self, wx.ID_ANY)
        grid_sizer_1.Add(self.onoffpanel, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.bitmap_button_1.Bind(wx.EVT_BUTTON, self.logo_click)
        self.choice_port.Bind(wx.EVT_CHOICE, self.can_port)
        self.button_1.Bind(wx.EVT_BUTTON, self.scan_pucks)
        self.choice_id.Bind(wx.EVT_CHOICE, self.select_id)
        self.text_id.Bind(wx.EVT_TEXT_ENTER, self.set_id)
        self.button_2.Bind(wx.EVT_BUTTON, self.set_id)
        self.button_8.Bind(wx.EVT_BUTTON, self.browse_fw)
        self.button_10.Bind(wx.EVT_BUTTON, self.file_to_p3)
        self.choice_test.Bind(wx.EVT_CHOICE, self.select_test)
        self.text_testvalue.Bind(wx.EVT_TEXT_ENTER, self.run_test)
        self.button_6.Bind(wx.EVT_BUTTON, self.run_test)
        # end wxGlade

    def calibrate_all(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_all' not implemented!")
        event.Skip()

    def calibrate_all_pucks(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_all_pucks' not implemented!")
        event.Skip()

    def update_all(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'update_all' not implemented!")
        event.Skip()

    def test_encoder(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'test_encoder' not implemented!")
        event.Skip()

    def calibrate_ibias(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_ibias' not implemented!")
        event.Skip()

    def calibrate_igainfactor(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_igainfactor' not implemented!")
        event.Skip()

    def calibrate_itiming(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_itiming' not implemented!")
        event.Skip()

    def calibrate_islope(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_islope' not implemented!")
        event.Skip()

    def calibrate_enczero(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_enczero' not implemented!")
        event.Skip()

    def calibrate_encdir(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_encdir' not implemented!")
        event.Skip()

    def calibrate_enclag(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'calibrate_enclag' not implemented!")
        event.Skip()

    def set_user_dir(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'set_user_dir' not implemented!")
        event.Skip()

    def tune_gains(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'tune_gains' not implemented!")
        event.Skip()

    def save_calibration(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'save_calibration' not implemented!")
        event.Skip()

    def open_support_page(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'open_support_page' not implemented!")
        event.Skip()

    def exit_program(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'exit_program' not implemented!")
        event.Skip()

    def factory_flash(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_flash' not implemented!")
        event.Skip()

    def factory_initpuck(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_initpuck' not implemented!")
        event.Skip()

    def factory_testall(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_testall' not implemented!")
        event.Skip()

    def factory_testflash(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_testflash' not implemented!")
        event.Skip()

    def factory_testram(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_testram' not implemented!")
        event.Skip()

    def factory_testee(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_testee' not implemented!")
        event.Skip()

    def factory_testamp(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_testamp' not implemented!")
        event.Skip()

    def factory_testenc(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'factory_testenc' not implemented!")
        event.Skip()

    def logo_click(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'logo_click' not implemented!")
        event.Skip()

    def can_port(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'can_port' not implemented!")
        event.Skip()

    def scan_pucks(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'scan_pucks' not implemented!")
        event.Skip()

    def select_id(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'select_id' not implemented!")
        event.Skip()

    def set_id(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'set_id' not implemented!")
        event.Skip()

    def browse_fw(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'browse_fw' not implemented!")
        event.Skip()

    def file_to_p3(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'file_to_p3' not implemented!")
        event.Skip()

    def select_test(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'select_test' not implemented!")
        event.Skip()

    def run_test(self, event):  # wxGlade: puckutilityapp_frame.<event_handler>
        print("Event handler 'run_test' not implemented!")
        event.Skip()

# end of class puckutilityapp_frame
