; This is a system-config file for P4 Motor Controllers.

; NOTE: When using paths, use absolute paths with public directories to ensure the system-config works across different users/computers.

; This template can be used to update a full system to desired firmware and configuration files.
; The fw_version is compared to each Pucks active firmware.
; If the fw_version does not match, the fw path binary file will be uploaded to the Puck.

[DEFAULT]
fw_version = 3.4.4
fw = C:\Users\Bailey\Downloads\Puck4-v3.4.4.ebin

; Each Entry contains a node from the system. Add / Update entries for each Puck.
; Match the correct id value for each Puck with the desired csv file. 
; The csv will automatically be uploaded to the Puck.

[ENTRY1]
id = 1
csv = C:\Users\Bailey\Downloads\P4-37-42V-20A-High-Force-Mag-v1.1.6-Batch2-2026-02-10.csv

[ENTRY2]
id = 5
csv = C:\Users\Bailey\Downloads\P4-37-42V-20A-High-Force-Mag-v1.1.6-Batch2-2026-02-10.csv

[ENTRY3]
id = 3
csv = C:\Users\Bailey\Downloads\P4-37-42V-20A-High-Force-Mag-v1.1.6-Batch2-2026-02-10.csv

; Use this template to add new entries. Replace asterisks (*) with desired values. 

; [ENTRY*]
; id = *
; csv = *