; This is a system-config file for P4 Motor Controllers.

; NOTE: When using paths, use absolute paths with public directories to ensure the system-config works across different users/computers.

; This template can be used to update a full system to desired firmware and configuration files.
; The fw_version is compared to each Puck's active firmware.
; If the fw_version does not match, the fw path binary file will be uploaded to the Puck.
; Individual entries can override fw_version and fw to use a different firmware per Puck.

[DEFAULT]
fw_version = 4.2.1
fw = "C:\Users\Bailey\puckutility\firmware\puck4.app.k64.release.4.2.1.bin"

; Each Entry contains a node from the system. Add / Update entries for each Puck.
; Match the correct id value for each Puck with the desired csv file. 
; The csv will automatically be uploaded to the Puck.

[ENTRY1]
id = 1
csv = "C:\Users\Bailey\puckutility\config\P4-16-DevKit-24V-v2.3.2-2026-04-06.csv"

; Use this template to add new entries. Replace asterisks (*) with desired values.
; Optionally include fw_version and fw to override the DEFAULT firmware for a specific Puck.

; [ENTRY*]
; id = *
; csv = *
; fw_version = *
; fw = *