#!/usr/bin/env bash
# Regenerate this app's wxGlade GUI (*_gui.py) from its configure-*.wxg.
#
# Why this exists:
#   * The plain `wxglade -g python file.wxg` CLI dies with "wx.App object must be
#     created first" (the no-GUI codegen path builds the app tree but never a
#     wx.App). This script creates a wx.App first, then runs wxGlade's codegen.
#   * It NEVER overwrites in place silently: it generates to a temp file and shows
#     a diff against the committed *_gui.py first. A hand-edit that never made it
#     into the .wxg shows up as drift here instead of being lost on regen.
#
# Usage:
#   scripts/regen-gui.sh           # dry run: show the diff only
#   scripts/regen-gui.sh --write   # regenerate after reviewing the diff
#
# Edit the .wxg (in wxGlade, or by hand), then run this. Never hand-edit *_gui.py.
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1

PY="$REPO_ROOT/.venv/bin/python"
[ -x "$PY" ] || { echo "ERROR: no .venv at $REPO_ROOT/.venv — run scripts/setup-venv.sh first." >&2; exit 1; }
"$PY" -c "import wxglade" 2>/dev/null || {
    echo "ERROR: wxGlade is not installed in the venv." >&2
    echo "       Run scripts/setup-pip.sh (without NO_DEV_TOOLS=1)." >&2
    exit 1; }

# Find the project .wxg (skip wxGlade backup copies like 'configure-x (copy).wxg').
WXG=$(ls "$REPO_ROOT"/configure-*.wxg 2>/dev/null | grep -v "(copy)" | head -1)
[ -n "$WXG" ] || { echo "ERROR: no configure-*.wxg found in $REPO_ROOT." >&2; exit 1; }

# Target *_gui.py comes from the .wxg's own 'path' attribute.
GUI_REL=$(grep -o 'path="[^"]*"' "$WXG" | head -1 | sed 's/^path="//; s/"$//')
[ -n "$GUI_REL" ] || { echo "ERROR: no path=\"...\" attribute in $(basename "$WXG")." >&2; exit 1; }
GUI="$REPO_ROOT/$GUI_REL"

TMP="$(mktemp "${TMPDIR:-/tmp}/regen-gui.XXXXXX.py")"
trap 'rm -f "$TMP"' EXIT

# Headless codegen with a wx.App created first (works around the CLI bug).
"$PY" - "$WXG" "$TMP" <<'PYEOF'
import sys, os, importlib.util
import wxglade as _pkg
PKG = os.path.dirname(_pkg.__file__); sys.path.insert(0, PKG)
import wx; _app = wx.App()  # keep a reference: an unassigned App gets GC'd before load
wxg, out = sys.argv[1], sys.argv[2]
sys.argv = ['wxglade', '-g', 'python', '-o', out, wxg]
spec = importlib.util.spec_from_file_location('wxg_cli', os.path.join(PKG, 'wxglade.py'))
m = importlib.util.module_from_spec(spec); sys.modules['wxg_cli'] = m
spec.loader.exec_module(m)
try: m.run_main()
except SystemExit: pass
PYEOF
[ -s "$TMP" ] || { echo "ERROR: wxGlade produced no output from $(basename "$WXG")." >&2; exit 1; }

echo "wxg : $(basename "$WXG")"
echo "gui : $GUI_REL"
echo
# Diff ignoring the cosmetic 'generated by wxGlade ... on <date>' header line.
DIFF_OUT=$(diff <(grep -v "generated by wxGlade" "$GUI" 2>/dev/null) \
               <(grep -v "generated by wxGlade" "$TMP") || true)
if [ -z "$DIFF_OUT" ]; then
    echo "In sync: $GUI_REL already matches the .wxg (only the header date would change)."
else
    echo "----- diff: committed $GUI_REL  vs  fresh regen -----"
    echo "$DIFF_OUT"
    echo "-----------------------------------------------------"
    echo "Review above: any line removed from the committed file is a hand-edit"
    echo "NOT in the .wxg — sync it into the .wxg before writing, or it is lost."
fi

if [ "$WRITE" != "1" ]; then
    echo
    echo "Dry run. Re-run with --write to overwrite $GUI_REL."
    exit 0
fi

"$PY" -m py_compile "$TMP" || { echo "ERROR: regenerated file failed py_compile; NOT writing." >&2; exit 1; }
cp "$TMP" "$GUI"
echo
echo "Wrote $GUI_REL (compiles OK)."
